/**
 * `vibebill pr [number] [--comment]` (v0.2, spec §13): cost a GitHub pull
 * request via the `gh` CLI. This file is the ONLY place vibebill ever invokes
 * `gh`, and `gh` is the only way vibebill talks to a forge — no direct
 * network calls, no tokens handled by us (spec §14.3.1 stays intact: `gh`
 * makes the network request, not vibebill).
 */

import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { z } from 'zod';

import { byCommit, rollup } from '../../core/aggregate.js';
import { CliUserError } from '../../core/errors.js';
import { totalTokens } from '../../core/types.js';
import { formatUsd } from '../../pricing/money.js';
import { formatTokens } from '../../render/format.js';
import { c, renderTable } from '../../render/table.js';
import type { CliContext, LedgerRow } from '../context.js';
import { checkAccounting, scopedRows } from '../context.js';
import type { CliIO } from '../io.js';
import {
  baseJson,
  exitCodeFor,
  fmtDateUTC,
  glyphs,
  invariantLines,
  moneyBreakdownToJson,
  planHeaderSuffix,
  planTotalSuffix,
  printJson,
  tokensToJson,
  truncate,
} from '../render.js';
import { vibebillVersion } from '../version.js';

const execFileP = promisify(execFile);

export interface PrOptions {
  /** PR number; null lets `gh` infer the PR for the current branch. */
  number: string | null;
  /** Post (or idempotently update) the cost comment on the PR. */
  comment: boolean;
}

/** Marker that makes the PR comment findable and updatable, never duplicated. */
export const COMMENT_MARKER = '<!-- vibebill-cost -->';

// gh output is an untrusted parse boundary like any other (spec §14.2).
const prViewSchema = z
  .object({
    number: z.number().int(),
    title: z.string(),
    baseRefName: z.string(),
    headRefName: z.string(),
    commits: z.array(z.object({ oid: z.string().min(1) }).passthrough()),
  })
  .passthrough();

const commentListSchema = z.array(
  z.object({ id: z.number().int(), body: z.string() }).passthrough(),
);

/** Run `gh` with args; translate the two expected failure modes to exit-1 errors. */
async function gh(repoRoot: string, args: string[]): Promise<string> {
  try {
    const { stdout } = await execFileP('gh', args, {
      cwd: repoRoot,
      maxBuffer: 16 * 1024 * 1024,
    });
    return stdout;
  } catch (err) {
    const e = err as NodeJS.ErrnoException & { stderr?: string };
    if (e.code === 'ENOENT') {
      throw new CliUserError(
        'GitHub CLI (gh) not found — the pr command needs it.',
        'Install it from https://cli.github.com and run `gh auth login`.',
      );
    }
    const detail = (e.stderr ?? e.message ?? '').trim().split('\n')[0] ?? '';
    throw new CliUserError(
      `gh ${args[0] ?? ''} ${args[1] ?? ''} failed: ${detail}`,
      'Check `gh auth status` and that this repo has an open PR (or pass the PR number).',
    );
  }
}

/** Fetch PR metadata (number, title, refs, commit oids) via `gh pr view`. */
async function fetchPr(
  repoRoot: string,
  number: string | null,
): Promise<z.infer<typeof prViewSchema>> {
  const args = ['pr', 'view'];
  if (number !== null) args.push(number);
  args.push('--json', 'number,title,baseRefName,headRefName,commits');
  const raw = await gh(repoRoot, args);
  let json: unknown;
  try {
    json = JSON.parse(raw);
  } catch {
    throw new CliUserError('gh pr view returned unparseable JSON.', 'Try upgrading gh.');
  }
  const parsed = prViewSchema.safeParse(json);
  if (!parsed.success) {
    throw new CliUserError('gh pr view returned an unexpected shape.', 'Try upgrading gh.');
  }
  return parsed.data;
}

/** Build the markdown body for the PR cost comment. */
export function buildCommentBody(
  ctx: CliContext,
  pr: { number: number; title: string },
  perCommitLines: string[],
  totalLine: string,
): string {
  const provenanceNote =
    ctx.plan === null
      ? 'measured from local agent transcripts'
      : `API-equivalent value consumed on a ${ctx.plan} subscription`;
  return [
    COMMENT_MARKER,
    `### vibebill — cost of PR #${pr.number}`,
    '',
    totalLine,
    '',
    ...perCommitLines,
    '',
    `_${provenanceNote}; attribution is probabilistic (confidence-marked). Generated by vibebill ${vibebillVersion()}._`,
  ].join('\n');
}

/** Create or idempotently update the marker comment via the GitHub REST API through gh. */
async function upsertComment(repoRoot: string, prNumber: number, body: string): Promise<'created' | 'updated'> {
  const nameWithOwner = (
    await gh(repoRoot, ['repo', 'view', '--json', 'nameWithOwner', '--jq', '.nameWithOwner'])
  ).trim();
  const listRaw = await gh(repoRoot, [
    'api',
    `repos/${nameWithOwner}/issues/${prNumber}/comments`,
    '--paginate',
  ]);
  let existing: number | null = null;
  try {
    const parsed = commentListSchema.safeParse(JSON.parse(listRaw));
    if (parsed.success) {
      for (const comment of parsed.data) {
        if (comment.body.includes(COMMENT_MARKER)) {
          existing = comment.id;
          break;
        }
      }
    }
  } catch {
    // Unparseable comment list: treat as no existing comment; worst case we
    // create a second marker comment rather than failing the command.
  }
  if (existing !== null) {
    await gh(repoRoot, [
      'api',
      '--method',
      'PATCH',
      `repos/${nameWithOwner}/issues/comments/${existing}`,
      '-f',
      `body=${body}`,
    ]);
    return 'updated';
  }
  await gh(repoRoot, [
    'api',
    '--method',
    'POST',
    `repos/${nameWithOwner}/issues/${prNumber}/comments`,
    '-f',
    `body=${body}`,
  ]);
  return 'created';
}

/** Run `vibebill pr`; returns the process exit code. */
export async function runPr(ctx: CliContext, opts: PrOptions, io: CliIO): Promise<number> {
  const check = checkAccounting(ctx.rows, ctx.ingest);
  const pr = await fetchPr(ctx.repoRoot, opts.number);
  const prHashes = new Set(pr.commits.map((c) => c.oid));

  const rows = scopedRows(ctx);
  const prRows: LedgerRow[] = rows.filter(
    (r) => r.entry.attribution.kind === 'commit' && prHashes.has(r.entry.attribution.hash),
  );
  const knownHashes = new Set(
    [...prHashes].filter((h) => ctx.commitByHash.has(h)),
  );
  const missing = prHashes.size - knownHashes.size;
  if (missing > 0) {
    ctx.warnings.push(
      `${missing} of ${prHashes.size} PR commits are not in the local attribution scope — ` +
        'fetch the PR branch and/or rerun with --all-refs for full coverage',
    );
  }

  const total = rollup(prRows.map((r) => r.entry));
  const perCommit = byCommit(prRows.map((r) => r.entry));
  const orderedHashes = pr.commits.map((c) => c.oid);
  const commentAction = opts.comment ? await postComment() : null;

  if (ctx.flags.json) {
    printJson(
      {
        ...baseJson('pr', ctx, check),
        pr: {
          number: pr.number,
          title: pr.title,
          base: pr.baseRefName,
          head: pr.headRefName,
          commits: prHashes.size,
          commitsInScope: knownHashes.size,
        },
        cost: moneyBreakdownToJson(total.cost),
        tokens: tokensToJson(total.tokens),
        events: total.events,
        sessions: total.sessions.size,
        byCommit: orderedHashes.map((hash) => {
          const r = perCommit.get(hash);
          return {
            hash,
            inScope: ctx.commitByHash.has(hash),
            cost: r === undefined ? null : { nanoUsd: r.cost.total.toString() },
            tokens: r === undefined ? 0 : totalTokens(r.tokens),
          };
        }),
        comment: commentAction,
      },
      (l) => io.out(l),
    );
    return exitCodeFor(check, ctx.flags.strict);
  }

  const g = glyphs();
  io.out(
    c.bold(
      `PR #${pr.number} ${g.dot} ${truncate(pr.title, 60)}${planHeaderSuffix(ctx.plan)}`,
    ),
  );
  io.out(c.dim(`${pr.headRefName} ${g.arrow} ${pr.baseRefName}, ${prHashes.size} commits`));
  io.out('');
  io.out(
    `cost of this PR: ${c.bold(formatUsd(total.cost.total))}${planTotalSuffix(ctx.plan)} ` +
      `(${formatTokens(totalTokens(total.tokens))} tokens, ${total.sessions.size} sessions)`,
  );
  io.out('');
  if (orderedHashes.length > 0) {
    io.out(
      renderTable(
        [
          { header: 'cost', align: 'right' },
          { header: 'hash' },
          { header: 'date' },
          { header: 'subject' },
        ],
        orderedHashes.map((hash) => {
          const r = perCommit.get(hash);
          const commit = ctx.commitByHash.get(hash);
          return [
            r === undefined ? `$0.00 ${g.human}` : formatUsd(r.cost.total),
            hash.slice(0, 7),
            commit === undefined ? '?' : fmtDateUTC(commit.authorTs),
            commit === undefined ? c.dim('(not in local scope)') : truncate(commit.subject, 48),
          ];
        }),
      ),
    );
    io.out('');
  }
  for (const line of invariantLines(check)) io.out(line);

  if (commentAction !== null) io.out(`PR comment ${commentAction}`);
  return exitCodeFor(check, ctx.flags.strict);

  /** Shared --comment path for both output modes. */
  async function postComment(): Promise<'created' | 'updated'> {
    const perCommitLines = [
      '| cost | commit | subject |',
      '|---:|---|---|',
      ...orderedHashes.map((hash) => {
        const r = perCommit.get(hash);
        const commit = ctx.commitByHash.get(hash);
        const cost = r === undefined ? '$0.00 (human?)' : formatUsd(r.cost.total);
        const subject = commit === undefined ? '_(not in local scope)_' : commit.subject;
        return `| ${cost} | \`${hash.slice(0, 7)}\` | ${subject.replace(/\|/g, '\\|')} |`;
      }),
    ];
    const totalLine =
      `**${ctx.plan === null ? 'Total measured cost' : 'Total API-equivalent value'}: ` +
      `${formatUsd(total.cost.total)}** (${formatTokens(totalTokens(total.tokens))} tokens, ` +
      `${total.sessions.size} sessions)`;
    const body = buildCommentBody(ctx, pr, perCommitLines, totalLine);
    return upsertComment(ctx.repoRoot, pr.number, body);
  }
}
